import { describe } from 'manten';
import { outputCommonjs } from './output-commonjs.ts';
import { outputModule } from './output-module.ts';
import { outputDual } from './output-dual.ts';
import { outputTypes } from './output-types.ts';
import { env } from './env.ts';
import { define } from './define.ts';
import { nativeModules } from './native-modules.ts';
import { target } from './target.ts';
import { minification } from './minification.ts';
import { packageExports } from './package-exports.ts';
import { wildcardExports } from './wildcard-exports.ts';
import { packageImports } from './package-imports.ts';
import { imports } from './imports.ts';
import { importsAlias } from './imports-alias.ts';
import { bin } from './bin.ts';
import { dependencies } from './dependencies.ts';
import { externalizeDependencies } from './externalize-dependencies.ts';
import { realDependencies } from './real-dependencies.ts';
import { srcDist } from './src-dist.ts';
import { sourcemap } from './sourcemap.ts';
import { typescript } from './typescript.ts';
import { cleanDist } from './clean-dist.ts';
import { license } from './license.ts';
import { packageYaml } from './package-yaml.ts';
import { importAttributes } from './import-attributes.ts';
import { watch } from './watch.ts';
import { packagejsonFilter } from './packagejson-filter.ts';
import { resolveJsToTs } from './resolve-js-to-ts.ts';

export const builds = (nodePath: string) => describe('builds', () => {
	outputCommonjs(nodePath);
	outputModule(nodePath);
	outputDual(nodePath);
	outputTypes(nodePath);
	env(nodePath);
	define(nodePath);
	nativeModules(nodePath);
	target(nodePath);
	minification(nodePath);
	packageExports(nodePath);
	wildcardExports(nodePath);
	packageImports(nodePath);
	imports(nodePath);
	importsAlias(nodePath);
	bin(nodePath);
	dependencies(nodePath);
	externalizeDependencies(nodePath);
	realDependencies(nodePath);
	srcDist(nodePath);
	sourcemap(nodePath);
	typescript(nodePath);
	cleanDist(nodePath);
	license(nodePath);
	packageYaml(nodePath);
	importAttributes(nodePath);
	watch(nodePath);
	packagejsonFilter(nodePath);
	resolveJsToTs(nodePath);
}, {
	parallel: process.platform === 'win32' ? 2 : 'auto',
});
