import { describe } from 'manten';
import { outputCommonjs } from './output-commonjs.ts';
import { outputModule } from './output-module.ts';
import { outputDual } from './output-dual.ts';
import { outputTypes } from './output-types.ts';
import { env } from './env.ts';
import { define } from './define.ts';
import { nativeModules } from './native-modules.ts';
import { target } from './target.ts';
import { minification } from './minification.ts';
import { packageExports } from './package-exports.ts';
import { wildcardExports } from './wildcard-exports.ts';
import { packageImports } from './package-imports.ts';
import { imports } from './imports.ts';
import { importsAlias } from './imports-alias.ts';
import { bin } from './bin.ts';
import { dependencies } from './dependencies.ts';
import { externalizeDependencies } from './externalize-dependencies.ts';
import { realDependencies } from './real-dependencies.ts';
import { srcDist } from './src-dist.ts';
import { sourcemap } from './sourcemap.ts';
import { typescript } from './typescript.ts';
import { cleanDist } from './clean-dist.ts';
import { license } from './license.ts';
import { packageYaml } from './package-yaml.ts';
import { importAttributes } from './import-attributes.ts';
import { watch } from './watch.ts';
import { packagejsonFilter } from './packagejson-filter.ts';
import { resolveJsToTs } from './resolve-js-to-ts.ts';

export const builds = () => describe('builds', () => {
	outputCommonjs();
	outputModule();
	outputDual();
	outputTypes();
	env();
	define();
	nativeModules();
	target();
	minification();
	packageExports();
	wildcardExports();
	packageImports();
	imports();
	importsAlias();
	bin();
	dependencies();
	externalizeDependencies();
	realDependencies();
	srcDist();
	sourcemap();
	typescript();
	cleanDist();
	license();
	packageYaml();
	importAttributes();
	watch();
	packagejsonFilter();
	resolveJsToTs();
}, {
	parallel: process.platform === 'win32' ? 2 : 'auto',
});
