name: Test
on:
  push:
  pull_request:

jobs:
  test:
    name: Test
    if: github.event_name == 'pull_request' || github.repository_owner == 'privatenumber'
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6

      - name: Configure temp directory (Windows)
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path D:\temp
          echo "TEMP=D:\temp" >> $env:GITHUB_ENV
          echo "TMP=D:\temp" >> $env:GITHUB_ENV
          echo "TMPDIR=D:\temp" >> $env:GITHUB_ENV

      - name: Install pnpm
        uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4

      - name: Setup Node.js
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
        with:
          node-version-file: .nvmrc

      # Install needs to happen after setup-node loads node_modules from cache
      - name: Install dependencies
        run: pnpm install

      - name: Lint
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: pnpm lint

      - name: Type check
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: pnpm type-check

      - name: Test
        run: pnpm test
